

export const hatOptions = [
    { value: "0x00", text: "Brown Fedora" },
    { value: "0x01", text: "Dark Brown Fedora" },
    { value: "0x02", text: "Green Fedora" },
    { value: "0x03", text: "Black Balaclava" },
    { value: "0x04", text: "White Balaclava" },
    { value: "0x05", text: "Grey Hat" },
    { value: "0x06", text: "Beige Hat" },
    { value: "0x07", text: "Sand Green Hat" },
    { value: "0x08", text: "Dark Green Hat" },
    { value: "0x09", text: "Grey Officer Hat" },
    { value: "0x0A", text: "Beige Officer Hat" },
    { value: "0x0B", text: "Dark Green Officer Hat" },
    { value: "0x0C", text: "Horns" },
    { value: "0x0D", text: "Black Turban with beige line" },
    { value: "0x0E", text: "Black Turban with red line" },
    { value: "0x0F", text: "Red Turban with beige line" },
    { value: "0x10", text: "Black Turban" },
    { value: "0x11", text: "Brown Turban" },
    { value: "0x12", text: "Blue Turban" },
    { value: "0x13", text: "Blue Turban with red line and broach" },
    { value: "0x14", text: "Green Turban with red line and broach" },
    { value: "0x15", text: "Black Turban with red line, broach and twig" },
    { value: "0x16", text: "Red Turban with beige line, broach and twig" },
    { value: "0x17", text: "Flat white Fedora with grey band" },
    { value: "0x18", text: "Flat green Fedora with brown band" },
    { value: "0x19", text: "Flat white Fedora with brown band" },
    { value: "0x1A", text: "Flat black Fedora" },
    { value: "0x1B", text: "White Desert Hat with black band" },
    { value: "0x1C", text: "White Desert Hat with brown band" },
    { value: "0x1D", text: "Grey Desert Hat" },
    { value: "0x1E", text: "Black Hood" },
    { value: "0x1F", text: "White Sailor Hat" },
    { value: "0x20", text: "Grey Sailor Hat" },
    { value: "0x21", text: "Red Sailor Hat" },
    { value: "0x22", text: "Pilot Hat" },
    { value: "0x23", text: "Baseball Cap blue" },
    { value: "0x24", text: "Baseball Cap white and blue" },
    { value: "0x25", text: "Headphones" },
    { value: "0x26", text: "Safari" },
    { value: "0x27", text: "White Cowboy Fedora" },
    { value: "0x28", text: "Brown Cowboy Fedora" },
    { value: "0x29", text: "Dark brown Cowboy Fedora" },
    { value: "0x2A", text: "Top Hat" },
    { value: "0x2B", text: "Wok Hat" },
    { value: "0x2C", text: "Fez Hat" },
    { value: "0x2D", text: "Builder Hat" },
    { value: "0x2E", text: "Grey Sailor Hat" },
    { value: "0x2F", text: "Blue Sailor Hat" },
    { value: "0x30", text: "Red Sailor Hat" },
    { value: "0x31", text: "Turban 2 black" },
    { value: "0x32", text: "Turban 2 blue" },
    { value: "0x33", text: "Turban 2 beige" }
];

export const hairOptions = [
    { value: "0x00", text: "Short Hair (Light Brown)" },
    { value: "0x01", text: "Short Hair (Black)" },
    { value: "0x02", text: "Short Hair (Orange)" },
    { value: "0x03", text: "Short Hair (Dark Grey)" },
    { value: "0x04", text: "Short Hair (Yellow)" },
    { value: "0x05", text: "Short Hair (Light Grey)" },
    { value: "0x06", text: "Long Hair (Light Brown)" },
    { value: "0x07", text: "Long Hair (Black)" },
    { value: "0x08", text: "Long Hair (Orange)" },
    { value: "0x09", text: "Pony Tail (Light Brown)" },
    { value: "0x0A", text: "Pony Tail (Yellow)" },
    { value: "0x0B", text: "Pony Tail (Black)" },
    { value: "0x0C", text: "Quiff (Black)" },
    { value: "0x0D", text: "Quiff (Light Brown)" },
    { value: "0x0E", text: "Quiff 2 (Black)" },
    { value: "0x0F", text: "Quiff 2 (Light Brown)" },
    { value: "0x10", text: "Dr E (Grey)" },
    { value: "0x11", text: "Dr E (Black)" },
    { value: "0x12", text: "Satipo (Black)" },
    { value: "0x13", text: "Satipo (Light Brown)" },
    { value: "0x14", text: "Marion (Light Brown)" },
    { value: "0x15", text: "Elsa (Yellow)" },
    { value: "0x16", text: "Willie (Yellow)" },
    { value: "0x17", text: "Librarian (Grey)" },
    { value: "0x18", text: "Librarian (White)" },
    { value: "0x19", text: "Donovan (Skeleton) Hair (White)" },
    { value: "0x1A", text: "Donovan (Skeleton) Hair (Grey)" }
];

export const headOptions = [
    { value: "0x00", text: "Indiana Jones" },
    { value: "0x01", text: "Indiana Jones (Professor)" },
    { value: "0x02", text: "Marion" },
    { value: "0x03", text: "Willie" },
    { value: "0x04", text: "Belloq" },
    { value: "0x05", text: "Barranca" },
    { value: "0x06", text: "Bandit Swordsman" },
    { value: "0x07", text: "Monkey Man" },
    { value: "0x08", text: "Brown with white facial hair" },
    { value: "0x09", text: "Elsa" },
    { value: "0x0A", text: "White with grey eye brows" },
    { value: "0x0B", text: "British Officer" },
    { value: "0x0C", text: "Army Intel Man A" },
    { value: "0x0D", text: "Female brown" },
    { value: "0x0E", text: "Chatter Lal" },
    { value: "0x0F", text: "Chatter Lal (Thuggee)" },
    { value: "0x10", text: "Captain Katanga" },
    { value: "0x11", text: "Kazim" },
    { value: "0x12", text: "Satipo" },
    { value: "0x13", text: "Donovan" },
    { value: "0x14", text: "Donovan (Skeleton)" },
    { value: "0x15", text: "Enemy Guard" },
    { value: "0x16", text: "Major Toht" },
    { value: "0x17", text: "With yellow hair" },
    { value: "0x18", text: "Fedora" },
    { value: "0x19", text: "Enemy Butler" },
    { value: "0x1A", text: "Thuggee" },
    { value: "0x1B", text: "Thuggee Priest" },
    { value: "0x1C", text: "Thuggee Slave Driver" },
    { value: "0x1D", text: "Sherpa Brawler" },
    { value: "0x1E", text: "Hovitos Tribesman" },
    { value: "0x1F", text: "Sherpa Brawler with sunglasses" },
    { value: "0x20", text: "Shanghai Hoodlum" },
    { value: "0x21", text: "Sherpa Brawler without facial hair" },
    { value: "0x22", text: "Mummy" },
    { value: "0x23", text: "Skeleton" },
    { value: "0x24", text: "Grail Knight" },
    { value: "0x25", text: "Chu Cin" },
    { value: "0x26", text: "DancingGirl A" },
    { value: "0x27", text: "DancingGirl B" }
];

export const weaponOptions = [
    { value: "0x00", text: "Pistol grey" },
    { value: "0x01", text: "Bazooka" },
    { value: "0x02", text: "Machine Gun" },
    { value: "0x03", text: "Rifle" },
    { value: "0x04", text: "Bow Arrow" },
    { value: "0x05", text: "Spear black" },
    { value: "0x06", text: "Sword" },
    { value: "0x07", text: "Grenade" },
    { value: "0x08", text: "Book" },
    { value: "0x09", text: "Bottle" },
    { value: "0x0A", text: "Spade" },
    { value: "0x0B", text: "Spanner" }
];

export const armsOptions = [
    { value: "0x00", text: "White" },
    { value: "0x01", text: "Medium neutral grey" },
    { value: "0x02", text: "Light warm grey / stone" },
    { value: "0x03", text: "Very dark grey / near-black" },
    { value: "0x04", text: "Very dark brown" },
    { value: "0x05", text: "Orange-brown / copper" },
    { value: "0x06", text: "Beige / sand" },
    { value: "0x07", text: "Light peach / skin-tone" },
    { value: "0x08", text: "Dark red / maroon" },
    { value: "0x09", text: "Tan / khaki" },
    { value: "0x0A", text: "Bright red" },
    { value: "0x0B", text: "Dark olive grey" },
    { value: "0x0C", text: "Light blue / sky blue" },
    { value: "0x0D", text: "Light tan / sandy beige" },
    { value: "0x0E", text: "Dark navy blue" },
    { value: "0x0F", text: "Muted purple / lavender" },
    { value: "0x10", text: "Dark red / blood red" },
    { value: "0x11", text: "Bright orange" },
    { value: "0x12", text: "Muted green / sage" },
    { value: "0x13", text: "Blue-grey / slate blue" },
    { value: "0x14", text: "Bright yellow" },
    { value: "0x15", text: "Medium green" },
    { value: "0x16", text: "Pure black" },
    { value: "0x17", text: "Dark brown" },
    { value: "0x18", text: "White" },
    { value: "0x19", text: "Medium blue" },
    { value: "0x1A", text: "Yellow-orange" },
    { value: "0x1B", text: "Bright blue" },
    { value: "0x1C", text: "Dark crimson red" },
    { value: "0x1D", text: "Neutral mid grey" },
    { value: "0x1E", text: "Very light blue / pale sky blue" }
];

export const handsOptions = [
    { value: "0x00", text: "Light Skin" },
    { value: "0x01", text: "Skin" },
    { value: "0x02", text: "Dark Skin" },
    { value: "0x03", text: "Red" },
    { value: "0x04", text: "Black" }
];

export const torsoOptions = [
    { value: "0x00", text: "Indiana Jones" },
    { value: "0x01", text: "Indiana Jones (Dinner)" },
    { value: "0x02", text: "Indiana Jones (Kali)" },
    { value: "0x03", text: "Indiana Jones (Army Disguise)" },
    { value: "0x04", text: "Indiana Jones (Desert)" },
    { value: "0x05", text: "Indiana Jones (Professor)" },
    { value: "0x06", text: "Indiana Jones (Ark Outro)" },
    { value: "0x07", text: "Marion" },
    { value: "0x08", text: "Marion (Cairo)" },
    { value: "0x09", text: "Marion (Evening Dress)" },
    { value: "0x0A", text: "Marion (Night Gown)" },
    { value: "0x0B", text: "Female Venice/Zepplin (Yellow)" },
    { value: "0x0C", text: "Marion (Ark Outro)" },
    { value: "0x0D", text: "Masked Bandit" },
    { value: "0x0E", text: "Bandit Swordsman" },
    { value: "0x0F", text: "Monkey Man" },
    { value: "0x10", text: "Army Intel Man B" },
    { value: "0x11", text: "Army Intel Man A" },
    { value: "0x12", text: "Barranca" },
    { value: "0x13", text: "Belloq (Jungle)" },
    { value: "0x14", text: "Belloq (Robes)" },
    { value: "0x15", text: "Belloq" },
    { value: "0x16", text: "Enemy Boxer" },
    { value: "0x17", text: "British Officer" },
    { value: "0x18", text: "British Soldier" },
    { value: "0x19", text: "Brody" },
    { value: "0x1A", text: "Dark skin female with white blouse" },
    { value: "0x1B", text: "Dark skin male with black top" },
    { value: "0x1C", text: "Dark skin male with white top" },
    { value: "0x1D", text: "Chatter Lal" },
    { value: "0x1E", text: "Chatter Lal (Thuggee)" },
    { value: "0x1F", text: "Wu Han" },
    { value: "0x20", text: "Lao Che" },
    { value: "0x21", text: "Chu Cin" },
    { value: "0x22", text: "Chuck" },
    { value: "0x23", text: "Colonel Dietrich" },
    { value: "0x24", text: "Colonel Vogel" },
    { value: "0x25", text: "Donovan" },
    { value: "0x26", text: "Donovan (Boss)" },
    { value: "0x27", text: "Donovan (Skeleton)" },
    { value: "0x28", text: "Elsa (Desert)" },
    { value: "0x29", text: "Elsa" },
    { value: "0x2A", text: "Enemy Butler" },
    { value: "0x2B", text: "Enemy Officer" },
    { value: "0x2C", text: "Enemy Officer (Nepal)" },
    { value: "0x2D", text: "Enemy Officer (Sub Pen)" },
    { value: "0x2E", text: "Enemy Officer (Desert)" },
    { value: "0x2F", text: "Female Venice/Zepplin (Pink)" },
    { value: "0x30", text: "Fedora" },
    { value: "0x31", text: "Grail Knight" },
    { value: "0x32", text: "Grave Robber 1" },
    { value: "0x33", text: "Hovitos Tribesman" },
    { value: "0x34", text: "Jungle Guide" },
    { value: "0x35", text: "Kazim Desert" },
    { value: "0x36", text: "Dark skin male suit black" },
    { value: "0x37", text: "Maharaja (Thuggee)" },
    { value: "0x38", text: "Maharaja" },
    { value: "0x39", text: "Major Toht" },
    { value: "0x3A", text: "Mola Ram" },
    { value: "0x3B", text: "Mummy" },
    { value: "0x3C", text: "Pankot Guard" },
    { value: "0x3D", text: "Henry Jones (Sr.)" },
    { value: "0x3E", text: "Village Elder" },
    { value: "0x3F", text: "Sallah (Desert)" },
    { value: "0x40", text: "Sallah" },
    { value: "0x41", text: "Satipo" },
    { value: "0x42", text: "Sherpa Gunner" },
    { value: "0x43", text: "Navy Suit Torso" },
    { value: "0x44", text: "Student Female green polka-dot" },
    { value: "0x45", text: "Thuggee Slave Driver" },
    { value: "0x46", text: "Thuggee Priest" },
    { value: "0x47", text: "Thuggee" },
    { value: "0x48", text: "Willie" },
    { value: "0x49", text: "Willie (Pyjamas)" },
    { value: "0x4A", text: "Willie (Dinner Suit)" },
    { value: "0x4B", text: "Willie (Ceremony)" },
    { value: "0x4C", text: "Young Indy" }
];

export const hipsOptions = [
    { value: "0x00", text: "White" },
    { value: "0x01", text: "Light Grey" },
    { value: "0x02", text: "Dark Grey" },
    { value: "0x03", text: "Black" },
    { value: "0x04", text: "Brown" },
    { value: "0x05", text: "Dark Brown" },
    { value: "0x06", text: "Dark Blue" },
    { value: "0x07", text: "Dark Green" },
    { value: "0x08", text: "Tan" },
    { value: "0x09", text: "Dark Red" },
    { value: "0x0A", text: "Light Blue" },
    { value: "0x0B", text: "Blue" },
    { value: "0x0C", text: "Dark Blue" },
    { value: "0x0D", text: "Light Green" },
    { value: "0x0E", text: "Green" },
    { value: "0x0F", text: "Dark Green" },
    { value: "0x10", text: "Light Brown" },
    { value: "0x11", text: "Brown" },
    { value: "0x12", text: "Dark Brown" },
    { value: "0x13", text: "Purple" },
    { value: "0x14", text: "Yellow" },
    { value: "0x15", text: "Orange" }
];

export const legsOptions = [
    { value: "0x00", text: "Black" },
    { value: "0x01", text: "White" },
    { value: "0x02", text: "Dark Blue" },
    { value: "0x03", text: "Light Blue" },
    { value: "0x04", text: "Red" },
    { value: "0x05", text: "Marion (Night Gown)" },
    { value: "0x06", text: "Light Tan" },
    { value: "0x07", text: "Dark Tan" },
    { value: "0x08", text: "Green" },
    { value: "0x09", text: "Unknown legs" },
    { value: "0x0A", text: "Grey" },
    { value: "0x0B", text: "Willie" },
    { value: "0x0C", text: "Purple" },
    { value: "0x0D", text: "Willie (Ceremony)" },
    { value: "0x0E", text: "Brown" },
    { value: "0x0F", text: "Dark Grey" },
    { value: "0x10", text: "Light Brown" },
    { value: "0x11", text: "Navy" },
    { value: "0x12", text: "Thuggee" },
    { value: "0x13", text: "Unknown white legs" },
    { value: "0x14", text: "Dark Green" },
    { value: "0x15", text: "Orange" },
    { value: "0x16", text: "Dancing Girl B (skin covered)" },
    { value: "0x17", text: "Dancing Girl A" }
];